spring.cache.ehcache.config=classpath:ehcache.xml
spring.jpa.properties.javax.persistence.sharedCache.mode=ALL
#spring.jpa.properties.javax.persistence.sharedCache.mode=ENABLE_SELECTIVE | ALL

server.max-http-header-size=2000000

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.mvc.format.date=yyyy-MM-dd
spring.mvc.format.date-time=yyyy-MM-dd HH:mm:ss
spring.mvc.format.time=HH:mm:ss
spring.mvc.format.date-time=iso

logging.config=classpath:log4j2.xml
#logging.level.org.hibernate.sql=DEBUG
#spring.jpa.show-sql=true
#logging.level.org.hibernate.type=TRACE 

spring.main.banner-mode=off
## set enviroment to build the application @valid values(dev,prod)
# e.g. dev - application-dev.property(local enviroment) , prod application-prod.property(production enviroment)
spring.profiles.active=dev

## for development comment the below line - The below line is use for context-path
# e.g.: http:localhost:9090/fms/api/v1/ctry/all
server.servlet.context-path=/FMS-fms

# App Properties
fms.app.jwtSecret= fms@SecretKey
fms.app.jwtExpirationMs= 86400000

