server.port=9090

spring.datasource.url=jdbc:sqlserver://10.2.158.7:1335;databaseName=fms
spring.datasource.username=sa
spring.datasource.password=StrongPass@123
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.show-sql=false
spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.hibernate.ddl-auto = update

#mail properties
spring.mail.host=smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=43a96640ac576e
spring.mail.password=84e291fd20e3d4
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
mail.smtp.debug=true
